In [95]:
import numpy as np 

In [96]:
base = np.array([[0, 1, 2, 3, 3, 2, 4],
                 [1, 0, 1, 2, 2, 1, 3],
                 [2, 1, 0, 1, 2, 2, 3],
                 [3, 2, 1, 0, 1, 2, 2],
                 [3, 2, 2, 1, 0, 1, 1],
                 [2, 1, 2, 2, 1, 0, 2],
                 [4, 3, 3, 2, 1, 2, 0]])

In [97]:
complement = np.array([[0, 1, 2, 2, 3],
                        [1, 0, 1, 2, 2],
                        [2, 1, 0, 1, 1],
                        [2, 2, 1, 0, 2],
                        [3, 2, 1, 2 ,0]])

In [98]:
base

array([[0, 1, 2, 3, 3, 2, 4],
       [1, 0, 1, 2, 2, 1, 3],
       [2, 1, 0, 1, 2, 2, 3],
       [3, 2, 1, 0, 1, 2, 2],
       [3, 2, 2, 1, 0, 1, 1],
       [2, 1, 2, 2, 1, 0, 2],
       [4, 3, 3, 2, 1, 2, 0]])

In [99]:
p = 2

n = p * 5  +2 
n

12

In [100]:
i = int((n-7) / 5)
i

1

In [101]:
new = base 

In [102]:
new = np.column_stack((new, base[:,6] +1))
new = np.column_stack((new, base[:,6] +2))
new = np.column_stack((new, base[:,6] +2))
new = np.column_stack((new, base[:,6] +1))
new = np.column_stack((new, base[:,6] +3))

base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))


In [103]:
new

array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3]])

In [104]:
new = np.vstack((new, new[6,:] +1))
new = np.vstack((new, new[6,:] +2))
new = np.vstack((new, new[6,:] +2))
new = np.vstack((new, new[6,:] +1))
new = np.vstack((new, new[6,:] +3))

In [105]:
new


array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 2, 3, 3, 2, 4],
       [6, 5, 5, 4, 3, 4, 2, 3, 4, 4, 3, 5],
       [6, 5, 5, 4, 3, 4, 2, 3, 4, 4, 3, 5],
       [5, 4, 4, 3, 2, 3, 1, 2, 3, 3, 2, 4],
       [7, 6, 6, 5, 4, 5, 3, 4, 5, 5, 4, 6]])

In [106]:
sh = new.shape[0]
sh -= 1

In [107]:
new[sh -4: , sh - 4:] =0

In [108]:
new

array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 0, 0, 0, 0, 0],
       [6, 5, 5, 4, 3, 4, 2, 0, 0, 0, 0, 0],
       [6, 5, 5, 4, 3, 4, 2, 0, 0, 0, 0, 0],
       [5, 4, 4, 3, 2, 3, 1, 0, 0, 0, 0, 0],
       [7, 6, 6, 5, 4, 5, 3, 0, 0, 0, 0, 0]])

In [109]:
complement

array([[0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [110]:
np.insert(complement, 0, np.array([0,0,0,0,0]), axis=0)


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [111]:
c =np.insert(complement, 0, np.array([0,0,0,0,0]), axis=0)
c

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [112]:
for i in range(100):
        
    if complement.shape[0] ==12 :
        break
    complement= np.insert(complement, 0, np.array([0,0,0,0,0]), axis=0)
    




In [113]:
complement


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [114]:
for i in range(100):
        
    if complement.shape[1] ==12 :
        break
    complement= np.insert(complement, 0, np.array([0,0,0,0,0,0,0,0,0,0,0,0]), axis=1)
    



In [122]:
complement

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 3],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 3, 2, 1, 2, 0]])

In [115]:
a = complement +new

In [121]:
a.sum() /2

196.0

In [117]:
a

array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 0, 1, 2, 2, 3],
       [6, 5, 5, 4, 3, 4, 2, 1, 0, 1, 2, 2],
       [6, 5, 5, 4, 3, 4, 2, 2, 1, 0, 1, 1],
       [5, 4, 4, 3, 2, 3, 1, 2, 2, 1, 0, 2],
       [7, 6, 6, 5, 4, 5, 3, 3, 2, 1, 2, 0]])

In [118]:
base

array([[0, 1, 2, 3, 3, 2, 4, 0, 0, 0, 0, 0],
       [1, 0, 1, 2, 2, 1, 3, 0, 0, 0, 0, 0],
       [2, 1, 0, 1, 2, 2, 3, 0, 0, 0, 0, 0],
       [3, 2, 1, 0, 1, 2, 2, 0, 0, 0, 0, 0],
       [3, 2, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [2, 1, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0],
       [4, 3, 3, 2, 1, 2, 0, 0, 0, 0, 0, 0]])

In [120]:
base.sum()

82