In [60]:
import numpy as np 

In [162]:
base = np.array([[0, 1, 2, 3, 3, 3, 4],
                 [1, 0, 1, 2, 2, 1, 3],
                 [2, 1, 0, 1, 2, 2, 3],
                 [3, 2, 1, 0, 1, 2, 2],
                 [3, 2, 2, 1, 0, 1, 1],
                 [2, 1, 2, 2, 1, 0, 2],
                 [4, 3, 3, 2, 1, 2, 0]])

In [163]:
completment = np.array([[0, 1, 2, 2, 3],
                        [1, 0, 1, 2, 2],
                        [2, 1, 0, 1, 1],
                        [2, 2, 1, 0, 2],
                        [3, 2, 1, 2 ,0]])

In [164]:
base

array([[0, 1, 2, 3, 3, 3, 4],
       [1, 0, 1, 2, 2, 1, 3],
       [2, 1, 0, 1, 2, 2, 3],
       [3, 2, 1, 0, 1, 2, 2],
       [3, 2, 2, 1, 0, 1, 1],
       [2, 1, 2, 2, 1, 0, 2],
       [4, 3, 3, 2, 1, 2, 0]])

In [165]:
p = 2

n = p * 5  +2 
n

12

In [166]:
i = int((n-7) / 5)
i

1

In [167]:
new = base 

In [168]:
new = np.column_stack((new, base[:,6] +1))
new = np.column_stack((new, base[:,6] +2))
new = np.column_stack((new, base[:,6] +2))
new = np.column_stack((new, base[:,6] +1))
new = np.column_stack((new, base[:,6] +3))

base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))


In [169]:
new

array([[0, 1, 2, 3, 3, 3, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3]])

In [170]:
new = np.vstack((new, new[6,:] +1))
new = np.vstack((new, new[6,:] +2))
new = np.vstack((new, new[6,:] +2))
new = np.vstack((new, new[6,:] +1))
new = np.vstack((new, new[6,:] +3))

In [171]:
new


array([[0, 1, 2, 3, 3, 3, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 2, 3, 3, 2, 4],
       [6, 5, 5, 4, 3, 4, 2, 3, 4, 4, 3, 5],
       [6, 5, 5, 4, 3, 4, 2, 3, 4, 4, 3, 5],
       [5, 4, 4, 3, 2, 3, 1, 2, 3, 3, 2, 4],
       [7, 6, 6, 5, 4, 5, 3, 4, 5, 5, 4, 6]])

In [174]:
sh = new.shape[0]
sh -= 1

In [180]:
new[sh -4: , sh - 4:] =0

In [181]:
new

array([[0, 1, 2, 3, 3, 3, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 0, 0, 0, 0, 0],
       [6, 5, 5, 4, 3, 4, 2, 0, 0, 0, 0, 0],
       [6, 5, 5, 4, 3, 4, 2, 0, 0, 0, 0, 0],
       [5, 4, 4, 3, 2, 3, 1, 0, 0, 0, 0, 0],
       [7, 6, 6, 5, 4, 5, 3, 0, 0, 0, 0, 0]])