In [52]:
import numpy as np 

In [53]:
base = np.array([[0, 1, 2, 3, 3, 2, 4],
                 [1, 0, 1, 2, 2, 1, 3],
                 [2, 1, 0, 1, 2, 2, 3],
                 [3, 2, 1, 0, 1, 2, 2],
                 [3, 2, 2, 1, 0, 1, 1],
                 [2, 1, 2, 2, 1, 0, 2],
                 [4, 3, 3, 2, 1, 2, 0]])

In [54]:
complement = np.array([[0, 1, 2, 2, 3],
                        [1, 0, 1, 2, 2],
                        [2, 1, 0, 1, 1],
                        [2, 2, 1, 0, 2],
                        [3, 2, 1, 2 ,0]])

In [55]:
base

array([[0, 1, 2, 3, 3, 2, 4],
       [1, 0, 1, 2, 2, 1, 3],
       [2, 1, 0, 1, 2, 2, 3],
       [3, 2, 1, 0, 1, 2, 2],
       [3, 2, 2, 1, 0, 1, 1],
       [2, 1, 2, 2, 1, 0, 2],
       [4, 3, 3, 2, 1, 2, 0]])

In [56]:
complement

array([[0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [143]:
def WPolythiophene(p):
    base = np.array([[0, 1, 2, 3, 3, 2, 4],
                 [1, 0, 1, 2, 2, 1, 3],
                 [2, 1, 0, 1, 2, 2, 3],
                 [3, 2, 1, 0, 1, 2, 2],
                 [3, 2, 2, 1, 0, 1, 1],
                 [2, 1, 2, 2, 1, 0, 2],
                 [4, 3, 3, 2, 1, 2, 0]])
    
    
    complement = np.array([[0, 1, 2, 2, 3],
                        [1, 0, 1, 2, 2],
                        [2, 1, 0, 1, 1],
                        [2, 2, 1, 0, 2],
                        [3, 2, 1, 2 ,0]])
    
    
    n= p*5 +2 #number of nodes 
    
    if n == 7 :
        return base.sum()/2  
    
    
    j = int((n-7) / 5)  # calculate of number of repeats
    
    
    new = base 
    for i in range(j):
        base = new
        
        
         
        
        a = base.shape[0]
        new = np.column_stack((new, base[:,a -1] +1))
        new = np.column_stack((new, base[:,a -1] +2))
        new = np.column_stack((new, base[:,a -1] +2))
        new = np.column_stack((new, base[:,a -1] +1))
        new = np.column_stack((new, base[:,a -1] +3))
        
        

        for k in range(5):
            base = np.column_stack((base, np.zeros(a)))



        new = np.vstack((new, new[a-1,:] +1))
        new = np.vstack((new, new[a-1,:] +2))
        new = np.vstack((new, new[a-1,:] +2))
        new = np.vstack((new, new[a-1,:] +1))
        new = np.vstack((new, new[a-1,:] +3))

        b = new.shape[0]  - 1   
        new[b -4: , b - 4:] =0
        
        


        C_col= complement.shape[1]

        for i in range(100):

            if complement.shape[0] == new.shape[0] :
                break
            complement= np.insert(complement, 0, np.zeros(C_col), axis=0)



        C_row = complement.shape[0]   

        for i in range(100):

            if complement.shape[1] == new.shape[1] :
                 break
            complement= np.insert(complement, 0, np.zeros(C_row), axis=1)
            
            
        new = new + complement
            
            
            




        
        
    return new

        
    
    

In [146]:
WPolythiophene(2)

array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 0, 1, 2, 2, 3],
       [6, 5, 5, 4, 3, 4, 2, 1, 0, 1, 2, 2],
       [6, 5, 5, 4, 3, 4, 2, 2, 1, 0, 1, 1],
       [5, 4, 4, 3, 2, 3, 1, 2, 2, 1, 0, 2],
       [7, 6, 6, 5, 4, 5, 3, 3, 2, 1, 2, 0]])

In [99]:
p = 2

n = p * 5  +2 
n

12

In [100]:
i = int((n-7) / 5)
i

1

In [57]:
new = base 

In [58]:
new = np.column_stack((new, base[:,6] +1))
new = np.column_stack((new, base[:,6] +2))
new = np.column_stack((new, base[:,6] +2))
new = np.column_stack((new, base[:,6] +1))
new = np.column_stack((new, base[:,6] +3))

base = np.column_stack((base, np.zeros(7)))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))
base = np.column_stack((base, np.array([0, 0, 0, 0, 0, 0, 0])))


In [59]:
new

array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3]])

In [60]:
base

array([[0., 1., 2., 3., 3., 2., 4., 0., 0., 0., 0., 0.],
       [1., 0., 1., 2., 2., 1., 3., 0., 0., 0., 0., 0.],
       [2., 1., 0., 1., 2., 2., 3., 0., 0., 0., 0., 0.],
       [3., 2., 1., 0., 1., 2., 2., 0., 0., 0., 0., 0.],
       [3., 2., 2., 1., 0., 1., 1., 0., 0., 0., 0., 0.],
       [2., 1., 2., 2., 1., 0., 2., 0., 0., 0., 0., 0.],
       [4., 3., 3., 2., 1., 2., 0., 0., 0., 0., 0., 0.]])

In [61]:
new = np.vstack((new, new[6,:] +1))
new = np.vstack((new, new[6,:] +2))
new = np.vstack((new, new[6,:] +2))
new = np.vstack((new, new[6,:] +1))
new = np.vstack((new, new[6,:] +3))

In [62]:
new


array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 2, 3, 3, 2, 4],
       [6, 5, 5, 4, 3, 4, 2, 3, 4, 4, 3, 5],
       [6, 5, 5, 4, 3, 4, 2, 3, 4, 4, 3, 5],
       [5, 4, 4, 3, 2, 3, 1, 2, 3, 3, 2, 4],
       [7, 6, 6, 5, 4, 5, 3, 4, 5, 5, 4, 6]])

In [63]:
sh = new.shape[0]
sh -= 1

In [64]:
new[sh -4: , sh - 4:] =0

In [65]:
new

array([[0, 1, 2, 3, 3, 2, 4, 5, 6, 6, 5, 7],
       [1, 0, 1, 2, 2, 1, 3, 4, 5, 5, 4, 6],
       [2, 1, 0, 1, 2, 2, 3, 4, 5, 5, 4, 6],
       [3, 2, 1, 0, 1, 2, 2, 3, 4, 4, 3, 5],
       [3, 2, 2, 1, 0, 1, 1, 2, 3, 3, 2, 4],
       [2, 1, 2, 2, 1, 0, 2, 3, 4, 4, 3, 5],
       [4, 3, 3, 2, 1, 2, 0, 1, 2, 2, 1, 3],
       [5, 4, 4, 3, 2, 3, 1, 0, 0, 0, 0, 0],
       [6, 5, 5, 4, 3, 4, 2, 0, 0, 0, 0, 0],
       [6, 5, 5, 4, 3, 4, 2, 0, 0, 0, 0, 0],
       [5, 4, 4, 3, 2, 3, 1, 0, 0, 0, 0, 0],
       [7, 6, 6, 5, 4, 5, 3, 0, 0, 0, 0, 0]])

In [66]:
complement

array([[0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [67]:
np.insert(complement, 0, np.array([0,0,0,0,0]), axis=0)


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [68]:
c =np.insert(complement, 0, np.array([0,0,0,0,0]), axis=0)
c

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [69]:
for i in range(100):
        
    if complement.shape[0] ==12 :
        break
    complement= np.insert(complement, 0, np.array([0,0,0,0,0]), axis=0)
    




In [70]:
complement


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 2, 2, 3],
       [1, 0, 1, 2, 2],
       [2, 1, 0, 1, 1],
       [2, 2, 1, 0, 2],
       [3, 2, 1, 2, 0]])

In [71]:
for i in range(100):
        
    if complement.shape[1] ==12 :
        break
    complement= np.insert(complement, 0, np.array([0,0,0,0,0,0,0,0,0,0,0,0]), axis=1)
    



In [76]:
complement.shape

(12, 12)

In [73]:
a = complement +new

In [74]:
a.sum() /2

196.0

In [77]:
a.shape

(12, 12)

In [118]:
base

array([[0, 1, 2, 3, 3, 2, 4, 0, 0, 0, 0, 0],
       [1, 0, 1, 2, 2, 1, 3, 0, 0, 0, 0, 0],
       [2, 1, 0, 1, 2, 2, 3, 0, 0, 0, 0, 0],
       [3, 2, 1, 0, 1, 2, 2, 0, 0, 0, 0, 0],
       [3, 2, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [2, 1, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0],
       [4, 3, 3, 2, 1, 2, 0, 0, 0, 0, 0, 0]])

In [120]:
base.sum()

82